seek-oss/logger

src/base/index.ts

These cost extra bytes and $$$ for every log message. I'm not aware of any benefit to logging these by default given that our primary runtime environments (Fargate, Lambda) are serverless.

fix: Drop hostname and pid

---

src/serializers/index.test.ts
src/serializers/index.ts

Addresses #9 
Make use of `res._header` to get response header info.
Making use of serializer in a bare-bones node http server produces the following output:
With this implementation, response header is provided to logger in a string format:
```
"HTTP/1.1 200 OK\r\ntest-header: abc\r\nDate: Sat, 30 Jan 2021 03:20:32 GMT\r\nConnection: keep-alive\r\nKeep-Alive: timeout=5\r\nContent-Length: 0\r\n\r\n"
```
We _could_ have the response header as key-value pairs by using `res.getHeaders()` which is cleaner and consistent with `req.headers` - see [here](https://nodejs.org/api/http.html#http_response_getheaders). However, the current logger's default configuration does not allow this, because the default formatter/trimmer converts the `getHeaders` method into a string, making it un-callable.

fix(serializer): Read from `res._header`

---

README.md
package.json
yarn.lock

This powers Pino's `prettyPrint` option and can be useful for local execution.
~~It does bloat the bundle a little.~~ Demoted to a peer dependency to reduce bloat

chore: Document `pino-pretty` usage

---

package.json

Fix warning found by `esbuild` and `webpack` related to the `sideEffects` property in `package.json`.
Change `sideEffects` value in `package.json` from string `"false"` to boolean `false`.
Fix is based on the assumption that the property is for consumers of this package that use `webpack`.
See https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
Fixes https://github.com/seek-oss/logger/issues/11

fix(package.json): sideEffects is a boolean

---

src/destination/index.ts
src/formatters/index.ts
src/index.test.ts
src/index.ts

Currently there's no way to redact specific fields within a string, you'd have to redact the entirety of the string via the `redact` option.  
This allows consumers to pass in a function that would have access to the full text log, and allow them to redact specific strings within it.
N/A
Related to https://github.com/SEEK-Jobs/indie-jepsen/pull/240.

feat: Add `redactText`

---

src/redact/index.ts

Looks like `tsc --declaration` doesn't like this otherwise.
https://github.com/seek-oss/logger/runs/5999772400?check_suite_focus=true#step:5:38

Vendor `redactOptions`

---

src/index.test.ts
src/index.ts

I would like to use provided `timestamp` logger option when creating the logger instance.
Currently, the input `timestamp` logger option is overridden by [the default timestamp function](https://github.com/seek-oss/logger/blob/master/src/index.ts#L40)
Use provided `timestamp` logger option if it is not undefined, otherwise use the default timestamp function.
This can be a breaking change since several places(e.g. [hirer-contracts-api](https://github.com/SEEK-Jobs/hirer-contracts-api/blob/master/src/util/logger.ts#L16), [hirer-budgets-api](https://github.com/SEEK-Jobs/hirer-budgets-api/blob/master/src/util/logging.ts#L45), and [etc.](https://github.com/search?q=org%3ASEEK-Jobs+%22%40seek%2Flogger%22+createLogger+timestamp&type=Code)) are using the timestamp logger option and this change …

feat: Respect custom `timestamp` logger option

---

README.md
package.json
src/index.test.ts
src/serializers/index.test.ts
src/serializers/index.ts
tsconfig.json

BREAKING CHANGE: Require Node.js 16.11+. Node.js 14 will reach end of life by April 2023.
https://nodejs.org/api/http.html#requestconnection
Accessing `.connection()` on the request object is now deprecated since Node 13. Switch to using `.socket()`
_How does this change address the problem?_
Let's ship it with https://github.com/seek-oss/logger/pull/59 ?

fix(serializers): use `.socket()` on the req serializer instead of `.connection()`

---

package.json
src/formatters/index.ts
src/index.test.ts
src/index.ts
src/serializers/index.test.ts
src/serializers/index.ts
yarn.lock

Fastify request/response objects are classes with getters, which rely on serializers to call them. The `dtrim` library was previously destroying the classes before they reach the serializer. This change prevents any objects/classes with a serializer from being trimmed.
- Bump `dtrim` to version which includes a `retain` option.
- Bump `pino-std-serializers` to add `errWithCause` serializer.
Adding `stdSerializers` directly to the serializers were adding non serializers to pino. https://github.com/pinojs/pino-std-serializers/blob/986ef19e19b9d68c2e821d948f066362a4f82311/index.d.ts#L109

feat: prevent objects with serializers from being trimmed

---

.changeset/moody-bobcats-travel.md
README.md
src/index.test.ts
src/index.ts
src/serializers/index.test.ts
src/serializers/index.ts
src/serializers/omitProperties.test.ts
src/serializers/omitProperties.ts
src/serializers/omitPropertiesSerializer.test.ts
src/serializers/omitPropertiesSerializer.ts
src/serializers/types.ts

Alternative to https://github.com/seek-oss/logger/pull/84
Pino has a limitation where you can either redact or remove specified redact.paths by setting redact.remove to true or false.
In some cases, it's reasonable to want to redact some properties e.g. headers.authorization so you know that you have an authorization header but in other cases, the header, e.g. x-envoy-peer-metadata only contributes to increasing the log message size and therefore cost.
To reduce costs, we should be able to remove the properties that are not relevant for diagnostic purposes.
- Properties containing headers that should be omitted were identified via this Splunk query over 1 business day:
```splunkspl
index="*" 
| fields *x-envoy-*
| fieldsummary
| rex mode=sed field=values "s~\[?\{\"value\":\"~~g …
```

feat: Omit specific headers by default

---

.changeset/moody-bobcats-travel.md
src/index.test.ts

`toMatchObject` accepts an object subset, which makes it hard to reliably test property removal. For example, #92 adds a happy-path test case "should omit defaultOmitHeaderNames by default" which unexpectedly passes even if the omission logic is removed.
These tests aren't great overall and I'd prefer them to use a more typical Jest structure so we can use `.only`s and the like, but this should be enough to get #92 through with confidence around regression testing.

Use `toStrictEqual` in root tests

---

src/serializers/index.test.ts
src/serializers/index.ts
src/serializers/omitPropertiesSerializer.ts

We don't want consumers to unintentionally mutate this constant.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

Freeze `DEFAULT_OMIT_HEADER_NAMES`

---

README.md

Add some guidelines for redacting some properties and removing (omitting) other properties from the logged object.
Update the readme with guidelines on redacting some and removing other properties and an "Omit Headers" section.
Resolves #83

Add redact guidelines

---

.changeset/healthy-pans-joke.md
README.md
src/index.test.ts
src/redact/index.ts

The following paths must be redacted due to their content:
- `header['user-email']`
- `headers['user-email']`
- `req.headers['user-email']`
- Adds the paths to `defaultRedact` in `src/redact/index.ts`.
- Adds tests to assert default redact paths are always redacted.
- Fixes issue where default redact paths were not redacted when an object was provided as the `redact` options.

fix: Merge default redact paths with custom redact paths

---

.changeset/neat-radios-ring.md
src/destination/mock.ts

Whoops. Makes #134 more usable.

createDestination: Use `Record` type for `stdoutMock.calls` and `stdoutMock.onlyCall()`

---

src/index.test.ts
src/serializers/index.ts

This [test](https://github.com/seek-oss/logger/blob/26f7f5409c53d295c7932a50952c587b184570a7/src/index.test.ts#L700-L726) fails in master with the following output, which can result in some quite nasty logs... I caught this in a few logs that were logging entire html documents 🫠 
Trim the returned objected from both the [err](https://github.com/pinojs/pino-std-serializers/blob/dc2ce14ebb9497d2ebe1a37c9f0da8d711ef5cc0/lib/err.js) and [errWithCause](https://github.com/pinojs/pino-std-serializers/blob/dc2ce14ebb9497d2ebe1a37c9f0da8d711ef5cc0/lib/err-with-cause.js#L47) serializers with the desired formatting options.

Trim objects that are serialized by `err` and `errWithCause`

---

.changeset/smooth-ties-look.md
src/formatters/index.ts
src/index.test.ts
src/index.ts
src/serializers/index.test.ts
src/serializers/index.ts
src/serializers/omitPropertiesSerializer.ts
src/serializers/types.ts

Adds changes and refactors based on suggestions from https://github.com/seek-oss/logger/pull/141
- Adds trimming to all serializers
- Reuses shared trimmer between serializers
- Excludes `stack` field from trimming in `err` and `errWithCause` serializers
- Defines the default `maxObjectDepth` once
- Condensed some related/duplicate tests

Add truncation to all serializers

---

docs/testing.md

In lieu of actually trying to fix this. (Naive thought is to mangle or discard the `transport` argument when our mock destination is passed, but that could be contentious.)

stdoutMock: Add disclaimer on custom transports

---

.changeset/ninety-bobcats-return.md
src/index.test.ts
src/index.ts

I believe this should be entirely optional & backwards compatible. Anything I'm missing in that aspect?

Add support for configuring custom log levels

---

.changeset/loud-moles-push.md
README.md
src/index.test.ts
src/index.ts

Alternate approach to fix ESM compatibility to bundling: https://github.com/seek-oss/logger/pull/190
This would require everyone to migrate their import once they've moved to ESM. We can probably code-mod something via skuba to fix the majority

Export create logger as a named export

---

docs/eeeoh.md

- Remove "DIY sample" as it may attract eyeballs and copy-paste
- Re-iterate `use: 'environment'` rec in base attribute section
- Sneak in a mention of aligning `env` with Automat workload hosting

Tweak base attribute doco

---

src/__snapshots__/index.test.ts.snap
src/eeeoh/eeeoh.ts
src/index.test.ts

Cold feet, I don't think we should force this via tooling as part of the initial migration ask.

Relax `env` validation

---

docs/eeeoh.md

I can't see an obvious way to manage "deep merging" of `.child()`
bindings so you can't actually specify `team` by itself.
https://redirect.github.com/pinojs/pino/issues/1645
An alternative would be to move `team` nesting from `eeeoh` to `base` so
it is accepted as an independent binding.
```diff
const logger = createLogger({
eeeoh: {
datadog: 'tin',
-     team: 'owner-a',
use: 'environment',
},
+   base: { team: 'owner-a' },
});
const childLogger = logger.child({
-   eeeoh: { datadog: 'tin', team: 'owner-b' },
+   team: 'owner-b',
});
```

RFC: Document that team cannot stand alone

---

.changeset/tall-horses-occur.md
jest.config.ts
package.json
pnpm-lock.yaml
src/eeeoh/eeeoh.ts
tsdown.config.mjs

`pure-parse` is taking a [little too long to respond to me](https://github.com/johannes-lindgren/pure-parse/pull/148) and I want to get a move on with ESM migration.
So I'm switching to [sury](https://github.com/DZakh/sury).

Use Other Validation Library
